project:
  type: website

website:
  title: "social-media-lab-quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



