project:
  type: website

website:
  title: "Social Media Lab"
  description: "Notes on computational social media analysis"
  page-navigation: true
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Getting Started"
        contents:
          - getting-started/index.qmd
          - getting-started/theory.qmd
          - getting-started/related-work.qmd
          - getting-started/tools.qmd
          - getting-started/literature-review-assistant.qmd
    #  - section: "Theory & Related Work"
      - section: "Data Collection"
        contents:
          - data-collection/ig-posts.qmd
          - data-collection/ig-stories.qmd
          - href: https://docs.google.com/document/d/19MAiqX7Vx1FcNJ44K-vSdnKDVC5gcFwtrSQiewnwW8A/edit?pli=1
            text: TikTok (External, DMI)
      - section: "Text Analysis"
        contents:
          - processing/index.qmd
          - processing/exploration.qmd
          - processing/classification.qmd
      - section: "Image Analysis"
      - section: "Evaluation"
        contents:
          - evaluation/index.qmd
      - projects/index.qmd
  navbar:
    logo: images/logo2.png
    tools:
        - icon: twitter
          href: https://twitter.com/michael_achmann
        - icon: github
          href:  https://github.com/michaelachmann/social-media-lab-quarto
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://github.com/michaelachmann/social-media-lab
        text: Notebooks 
      
  cookie-consent: true
  twitter-card: true
  site-url: https://social-media-lab.net

execute:
  freeze: auto

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

resources:
  - CNAME

