project:
  type: website

website:
  title: "Notes on (Computational) Social Media Research"
  page-navigation: true
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Getting Started"
        contents:
          - getting-started/index.qmd
    #  - section: "Theory & Related Work"
      - section: "Data Collection"
        contents:
          - data-collection/index.qmd
    #  - section: "Analysis"
      #- current-projects.qmd
  navbar:
    logo: images/logo.png
    tools:
        - icon: twitter
          href: https://twitter.com/michael_achmann
        - icon: github
          href:  https://github.com/michaelachmann/social-media-lab
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
  cookie-consent: true
  twitter-card: true
  site-url: https://social-media-lab.net


execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

resources:
  - CNAME

