---
format: 
  html: default
title: "Introduction to SMA"
date: 2023-10-23
bibliography: ../literature.bib
author:
  - name: Michael Achmann-Denkler
    id: ma
    orcid: 0000-0002-4754-7842
    email: michael.achmann@informatik.uni-regensburg.de
license: CC BY
---

Social Media Analyses (SMA) are used both, in academia and in professional settings. Depending on the research agenda, different methodologies may be applied [@Kanthawala2022-zu; @Rejeb2022-xr]. In our course, we focus on the academic exploration of Social Media. We place particular emphasis on questions related to media, politics, and society. This represents a confluence of communication science and political science, intertwined with computational methods.

Bridging this discussion, there are several disciplines pivotal to the academic analysis of social media data at this intersection: @Lazer2009-mp outlined in an influencial article **computational social science** as an emerging field that built on the ability to collect and analyze vast amounts of data. The goal of the computational social science, according to this article, is to reveal patterns in human interactions, benefiting from various data sources such as emails, phone records, online social networks, and other digital traces left by individuals. We are going to concentrate on social media data, a type of data described by @Quan-Haase2022-db as incidental, since the data exists and is being created, no matter the researchers observing them -- or not. One special type of data, Instagram stories, even have an ephemeral character. 24 hours after posting the story expires -- becoming invisible for followers and researchers alike [see also @Leaver2020-cj on the importance of stories]. @Van_Atteveldt2018-ly noted a surge in the use of computational methods in communication science, attributing it to three primary factors: the availability of digital data, sophisticated data analysis tools, and the emergence of cost-effective, potent processing capabilities complemented by accessible computing infrastructure. Building on this perspective, @Haim2023-or sees the **computational communication science** as a sub-discipline of communication science that addresses digitally altered objects of research, which require computational approaches to tackle to amount and complexity of this special type of data.

In the realm of **digital humanities**, computational approaches to text analysis have a long history, influenced by concepts such as **distant reading** [@Moretti2000-kj] and **macroanalysis** [@Jockers2013-hu]. Manovich picks up these concepts in his [**cultural analytics**](#cultural-analytics), see below. Lately also **distant viewing** has been outlined, as "a methodological and theoretical framework for the study of large collections of visual materials" [@Arnold2019-ls]. I see potential in integrating approaches and methods from the digital humanities into social media analysis. Vice versa, there's also potential in utilizing methods used for social media analysis to address questions in the humanities.

Challanges for social media analyses have been outlined by @Quan-Haase2022-mx: the role of theory, representativeness of data, scale, multimodality, data accessability, and legal and ethical considerations. Through our semester we are going to work on several of those challanges: In the *Operationalization* session we are going to talk about data-driven approaches [bearing in mind @Anderson2008-cq], as well as theories as basis for your research questions and operationalizations. The representativeness of data will be the challenge for our data collection sessions: We will not just answer *how* to collect data, but also *what* data to collect. The two challenges left are at the centre of our seminar: Our answer for the challenge of scale is to apply computational methods for data analysis, to process data at scale. Multimodality is another key issues of this seminar: We want to *computationally* process *visual* (or *multimodal*) data. We will talk about accessability problems thorugh our data collection classes, and talk about legal and ethical issues on this page.

Keeping these introductory considerations in mind, we immerse into a short outline of two theories: [Cultural Analytics](#cultural-analytics) and [Digital Methods](#digital-methods), as foundational elements for social media research. Subsequently, we'll address the ethical and legal challenges associated with analyzing social media. We'll conclude the chapter by presenting an array of methodologies. In the [related work](related-work.qmd) chapter, you'll find an overview of research on Instagram and TikTok content, even extending beyond our primary topics of interest.

::: {.callout-note}
The intent of this article is to provide a brief introduction to the field of computational social media analysis, tailored for my [Winter 2023/24 seminar](index.qmd). It offers only a cursory glance at various theories and methodologies. As such, please do not regard the content of this page as a definitive scientific piece. Instead, view it as a compass to guide and inspire your own research endeavors.
:::

## Cultural Analytics
Cultural analytics, as explained in the introductory chapter of the book "Cultural Analytics" by Lev Manovich, is a field that uses computers to analyze and understand large amounts of cultural information or "big cultural data". This might include exploring big collections of images, videos, or other media data to see patterns and trends that are happening in digital culture. Manovich talks about some key questions and challenges in cultural analytics. For example, one big question is whether we should focus on finding common themes and patterns in our data, or whether we should pay more attention to things that are unusual or rare. Also, while cultural analytics can be a powerful tool for understanding aspects of culture, especially in the digital world, Manovich tells us to be aware of its limits. He says that computers and data analysis can tell us a lot, but they can't understand culture in the rich and deep way that humans can, especially when it comes to understanding things like aesthetics (beauty, style, etc.). So, while cultural analytics can help us see large scale patterns and trends in culture, Manovich advises us to also appreciate and be aware of what it can’t see or understand. The field of cultural analytics then becomes a space where we use computational tools to explore and question culture, while also being mindful of the limitations and challenges of using these tools [@Manovich2020-qq]. 

## Digital Methods
"Digital Methods," as introduced by @Rogers2013-ja, proposes a paradigm wherein the internet is both a site and a source for research, especially for social media studies. Unlike conventional research approaches that see the internet merely as a tool or data source, Rogers advocates for a methodology that is intrinsically web-centric, understanding and employing the unique dynamics and mechanics of the digital medium itself. And example for a digital methods research project is understanding algorithmic operations, especially of search engines like Google, and comprehending their impact on digital culture, information accessibility, and user engagement. This perspective is important to explore the foundations of how information is organized, ranked, and accessed online. Studying the digital medium itself means to study web-native phenomena such as hyperlink networks, search engine behaviors, and social media activities to uncover patterns, tendencies, and hierarchical structures within digital cultures and societies. 

The concepts of cultural analytics and digital methods will guide us through our semester and our projects: We borrow the idea to use computational methods in order to understand "big cultural data" form Manovich and the concept of studying the digital medium itself from Rogers. Throughout the semester will enrich our projects with more focused literature and theory based on the research interests. Beyond these foundations, we will borrow from i.e. the Computational Social Sciences [@Lazer2009-mp], the concept of Distant Viewing [@Arnold2019-ls], or [Grammars of Action](#platform-vernaculars--grammars) [@Agre1994-qi; @Gerlitz2018-pn; @Bainotti2020-rn; @Omena2020-jk], and [Platform Vernaculars](#platform-vernaculars--grammars) [@Gibbs2015-se].

## Legal & Ethical Challenges

::: {.callout-warning}
This subchapter scratches the surface. Recommended reading: @Haim2023-or pp. 62--69; 126--128.
:::

When working with social media data we're dealing with personal information. As such we need to take into account legal and ethical considerations. From the legal perspective we need to focus on two aspects: The ownership of the data, and -- when dealing with personal data -- the GDPR. For the latter we need to take into account consent and should think about pseudonymisation or anonymisation of our data [@Haim2023-or]. Further, the German *Urheberrecht*, the equivalent of the anglo-saxon copyright law (there are important differences, [see *Bundeszentrale für politische Bildung*](https://www.bpb.de/themen/digitalisierung/urheberrecht/169971/urheberrecht-und-copyright/) for a synopsis), defines exceptions for scientific research: The @Rat_fur_Sozial-_und_Wirtschaftsdaten_RatSWD2019-re publication takes a closer look at the database law and provides some practical guidance.

The importance of the legal perspective social media research  grew recently: Following the [Cambridge Analytica scandal](https://en.wikipedia.org/wiki/Facebook%E2%80%93Cambridge_Analytica_data_scandal) Meta platforms (like Instagram) started closing down on APIs, which would have offered a legal and accepted (by the plattform) point of access for researchers. I recommend to read McCrow-Young's [-@McCrow-Young2021-pg] article as she demonstrates how academic research may be interrupted by platform changes, like the closure of the Instagram-API in the wake of the incident. Post-API social media research found creative way to access the data: @Bainotti2020-rn, for example, took a unique approach for data collection by capturing Instagram content through YouTube videos. Recent publications on Instagram analyses, and most approaches in our future session, rely on crawling and scraping. @Venturini2019-ve see a chance in the API-closure and argue that these techniques are "more than a ‘necessary evil’", as it might force researchers to come back to (digital) field work.

Finally a word about reserach ethics. While the GDPR provides a rigid legal framework for dealing with personal information, I'd like to recommend the article "But the Data is Already Public" by @Zimmer2010-zh. The article documents how, in a matter of days, an anonymous dataset of 1700 facebook profiles became (partly) deanonymized. Based on this case study, the author compiles ethical concerns for future research, which we should also incorporate into our work.


## Methodology
In this chapter we are going to take a look at different methods for use with social media reserach, and particularily, with our projects. We are going to use [(Visual) Content Analysis](#visual-content-analysis) to understand the content of posts and stories. The concept of [Plattform Affordances](#platform-affordances) will help us understand these posts and stories as embedded in the platform and its available functions and options. Finally, the idea of [Platform Vernaculars & Grammars](#platform-vernaculars--grammars) will help us to wire everything up, to discover patterns and trends in how users communicate and engage on these platforms.

### (Visual) Content Analysis
We are going to apply quantitative content analyses to our corpora. The quantitative approach we are going to operationalize our theory-based interests and questions using formal and / or content features. Next, we need to apply the operationalization to the documents, in form of human annotations or computational coding [see @Doring2016-ul]. 
@Doring2016-ul outline a general approach to content analysis, @Rose2016-qb in contrast concentrates on visual content analyses. She suggests four steps: 

> 1. "Finding your Images.
> 2. Devising your categories for coding.
> 3. Coding the images.
> 4. Analysing the results." -- [@Rose2016-qb ch. 5]

The challenge of the first step is the sampling: Even with computational approaches, is it feasible to collect **everything**? The cultural analytics approach suggests such a goal, e.g. in order to obtain data and traces of subcultures. Due to practical limitations also Manovich's works use an approach to break the large amount of available data into a smaller portion [see @Hochman2013-gh]. This approach is called sampling, @Rose2016-qb introduces several sampling approaches like *random, stratified, systematic,* or *cluster* sampling. @Doring2016-ul provide a deeper look into sampling strategies.

The codes, for the second step, may be devised from a qualitative exploration of the data or theories and related work. On coding there exists another large body of literature, like the Grounded Theory **Ergänze Zizazion** and Ethnic Coding Approach **Zitation**. In context of our projects we are going to use both approaches: We will annotate a subset of our data as ground-truth while coding the total data using computational approaches. 

For the final analysis we are going to apply statistical data analyses. For an initial understanding of our data we will start with some exploratory analyses, e.g. plotting the data. In combination with the two approaches below, the platform affordances and platform vernaculars & grammars we may discover patterns of social media use. In most cases, our projects will compare different groups: These groups might be different user types (e.g. Politician Accounts vs. Party Accounts), or different Posts types (e.g. Posts vs. Stories), or different platforms (e.g. Instagram vs. TikTok). 


### Platform Affordances
@Bossetta2018-lk provides an overview of the concept of affordances and their application in social media analyses. He traces the term back to boyd and Papacharissi & Yuan who argued "that  digital  communication  tech-
nologies provide structural affordances to agents" [p. 473 @Bossetta2018-lk]. There are two important take-aways from his work: 1) The concept of affordances is not used consistently, and 2) the platforms shape affordances and thereby how users interact with the platform. @Bainotti2020-rn used the "Instagram-specific digital objects" as codes for their analysis of stories, linking the concept of affordances in the context of Instagram to the use of stickers. 

In the context of our seminar we might consider the following elements as platform affordances:

| TikTok   	| IG -- Posts 	| IG -- Stories 	|
|----------	|-------------	|---------------	|
| Likes    	| Likes       	| Sliders       	|
| Comments 	| Comments    	| Votes         	|
| Shares   	| Views       	| Questions     	|
| Music    	| Mentions    	| Mentions      	|
| Hashtags 	| Hashtags    	| Hashtags      	|
| ...      	| ...          	| Locations     	|
|          	|             	| ...            	|

::: {.callout-tip}
## Question
Did you spot the difference between some of the listed affordances? Likes and comments, for instance, are reactions to posts. Would you consider these features as affordances? Let's discuss this is in class!
:::


### Platform Vernaculars & Grammars
**TODO: Umschreiben, damit es nicht gleich wie im Paper ist!!!**
'Grammars' have been explored in previous research on Instagram stories \citep{Bainotti2020-rn, Omena2020-jk}. It has initially been developed within the context of privacy. There, grammars of action categorize activities based on specific action types recognized by an accounting scheme, organizing and structuring them. Applying a grammar to an activity facilitates data collection and analysis, uncovering patterns and insights. As a result, grammars of action serve as a valuable tool for capturing behavioral data, applicable to various purposes including surveillance and targeted advertising [@Agre1994-qi]. The concept has first been applied to social media data by @Gerlitz2018-pn who conducted a Twitter analysis employing grammars of action to gain a better understanding of the client landscape and platform-stakeholder relations.
@Omena2020-jk introduce a "grammar of hashtags", which they see as the modes of action attached to hashtagging and how they are captured and organized by the platform. Grammars are merely one pillar of the three layers that the authors propose to capture hashtag engagement. They also look at the visibility of the content and actors as well as the visual and textual content. Finally, \citeauthor{Bainotti2020-rn} (\citeyear{Bainotti2020-rn}) picked up the concept of grammars to describe typical structures they found in ephemeral Instagram Stories. They see grammars as a key to understand aesthetic norms characterizing Stories in combination with actions offered by the platform. Thus, they see grammars to "take[...] into consideration the visual elements and how they are combined in their compositional modality [@Rose2016-qb], the cultural meaning they reflect, and the role of the platforms in prompting them." [p. 10, @Bainotti2020-rn]. @Gibbs2015-se were similarly concerned with the "combination of styles, grammars, and logics" of social media platforms, which they tried to capture as platform vernaculars. The vernacular is shaped from two ends, the platform affordances and the communication practices and habits of its users. 


## Summary 
In this chapter we have positioned ourselfes between several disciplines: The computational social science, computational communication science, and digital humanities. In this position, we see social media data as trace data of human and social behaviour. The digitalness of our subject is, however, just one side of the coin: Follwing the theoretical frameworks of Digital Methods and Cultural Analytics, we want to conduct our analyses *computationally* with the aim to uncover patterns and trends of user behaviour on social media plattforms. Methodologically we can draw from quantitative content analysis, and the concept of platform affordances as features, and apply the concept of platform vernaculars and grammars to make sense of these feautures.


## Additional Resources

### Conferences
* International Conference on Social Media & Society
* IC²S² 2022
* ICWSM
* AoIR
* WebSci
* International Conference on CMC and Social Media Corpora for the Humanities

### Journals
* New Media & Society
* Big Data & Society

### Textbooks
* @Rose2016-qb: Visual Methodologies: An Introduction to Researching with Visual Materials.
* @Haim2023-or: Computational Communication Science: Eine Einführung.
* @Quan-Haase2022-mx: The SAGE handbook of social media research methods.

### Online Resources 
* [Richard Rogers: Social Media Research with Digital Methods (YouTube)](https://www.youtube.com/watch?v=PtSNZfYKRnk)

::: {.callout-note}
Do you know of any ressources to be added to this list? Drop me a line: [michael.achmann@ur.de](mailto:michael.achmann@informatik.uni-regensburg.de).
:::

--- 

### References

::: {#refs}
:::